# From: https://github.com/jekyll/minima/issues/717#issuecomment-1460912086

# Disable using the latest Minima release
#theme: minima
# And instead pull straight from GitHub via jekyll remote theme
remote_theme: jekyll/minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: solarized-light
